### ISSUE TITLE
Error with 1.0.1

### ISSUE THREAD

**Issue by CGMossa** [orlp/slotmap#53] opened 2021-01-08 23:26 UTC
I'm unsure what is happening and why it is happening, but these lines from the `lib.rs`

```rust

#[cfg(test)]
#[macro_use]
extern crate quickcheck;

#[cfg(test)]
extern crate serde_json;

```

are making an error with the text `unresolved extern crate`.

I don't know what is going on here.

**Comment by CGMossa** [comment] 2021-01-08 23:35
I'm trying to dive deeper into this,.. And I believe there is something wrong with this:

```rust

#[cfg(feature = "serde")]
#[doc(hidden)]
#[macro_export]
macro_rules! __serialize_key {
    ( $name:ty ) => {
        impl $crate::__impl::Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: $crate::__impl::Serializer,
            {
                self.data().serialize(serializer)
            }
        }

        impl<'de> $crate::__impl::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: $crate::__impl::Deserializer<'de>,
            {
                let key_data: $crate::KeyData =
                    $crate::__impl::Deserialize::deserialize(deserializer)?;
                Ok(key_data.into())
            }
        }
    };
}
```
where it is saying that my new key type doesn't have a `self.data` for `&MyKeyType`.

**Comment by CGMossa** [comment] 2021-01-09 00:21
Somehow the trait that is being implemented.. is not in scope simultanously. (maybe rust macros are too hygienic).
I suggest this is a fix:

```rust

#[cfg(feature = "serde")]
#[doc(hidden)]
#[macro_export]
macro_rules! __serialize_key {
    ( $name:ty ) => {
        impl $crate::__impl::Serialize for $name {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: $crate::__impl::Serializer,
            {
                $crate::Key::data(self).serialize(serializer)
            }   
        }
[omitted]
```

**Comment by orlp** [comment] 2021-01-09 00:45
Can you give me the exact Rust version and feature flags you're using to reproduce this?

**Comment by CGMossa** [comment] 2021-01-09 00:52
Uh, I hope that's not the problem..

```rust
 rustc --version
rustc 1.51.0-nightly (61f5a0092 2021-01-04)
```
And I'm just using

```toml
slotmap = { path = "../slotmap", features = ["serde"] }
```

**Comment by orlp** [comment] 2021-01-09 00:54
I don't understand why this doesn't show up for me in `cargo +nightly test --features serde` - why did it slip through my testing?

**Comment by CGMossa** [comment] 2021-01-09 01:03
I don't know what to tell you. I just ran this command on the current master-branch, and I got no errors as well.
However, I did make a whole new project, and I only had this in `lib.rs`:

```rust
use slotmap::new_key_type;
new_key_type! {
    struct FarmId;
}
```

and I got this error.. 

I don't know what to tell you..

**Comment by orlp** [comment] 2021-01-09 01:05
I will investigate this in a bit.

**Comment by orlp** [comment] 2021-01-09 01:59
I know why this slipped through my testing. I have `use slotmap::*` in all my tests, which makes sense and is always fine - with one exception: macros.

Macros get expanded in the scope of the *caller*, so in this case a trait use (`Key`) was missing, but not in my tests. Will fix now.

**Comment by orlp** [comment] 2021-01-09 02:16
@CGMossa I'm not accepting your pull request because I'm breaking it up into smaller changes, adding tests to prevent this in the future, etc. But this will be fixed in an upcoming patch (today or tomorrow most likely).

As a workaround for now you can add an explicit `use slotmap::Key;` to bring the `Key` trait into scope, which will allow the macro to work.

**Comment by CGMossa** [comment] 2021-01-09 13:13
That's totally okay. 
I was just trying to help really. 
You can close to issue now.

**Closed** 2021-01-09 13:15 UTC

**Comment by mightyiam** [comment] 2021-01-09 15:11
This is not the same as [the error that can be seen in my CI](https://github.com/mightyiam/bookkeeping/pull/28/checks?check_run_id=1673783794), is it?

**Comment by orlp** [comment] 2021-01-09 18:29
@mightyiam No, that is because `slotmap` 1.0+ has a minimum required Rust version of 1.49, which you can see in the warning:

> warning: slotmap requires rustc => 1.49.0

I should however add that to the documentation and readme, and I will in the next patch.
